package Lab7;
import java.awt.*;
import simView.*;

public class RRSM extends ViewableDigraph
{

	final int NODE = 4;		//노드개수  
	final int QUEUE = 2;	//큐사이즈
	
	
	
	
	public RRSM()
	{
		super("gpt");
    	
		ViewableAtomic g = new genr("genr", 30);
		ViewableAtomic s = new scheduler("scheduler", 0, NODE);	//스케쥴링하는데에 시간 안 쓸 것  
		ViewableAtomic t = new transd("transd", 3000, NODE);
    	
		add(g);
		add(s);
		add(t);
  
		addCoupling(g, "out", s, "in");
		addCoupling(g, "out", t, "ariv");
		addCoupling(t, "out", g, "in");
		
		for(int i = 1; i <= NODE; i++) {									//
			ViewableAtomic p = new processor("processor"+i, 300, QUEUE);
			add(p);
			
			addCoupling(p, "out1", t, "solved");
			addCoupling(p, "out2", t, "loss");
			
			addCoupling(s, "out"+i, p, "in");
			
			
			
		}
		
		
	}

    
    /**
     * Automatically generated by the SimView program.
     * Do not edit this manually, as such changes will get overwritten.
     */
    public void layoutForSimView()
    {
        preferredSize = new Dimension(988, 646);
        ((ViewableComponent)withName("scheduler")).setPreferredLocation(new Point(218, 205));
        ((ViewableComponent)withName("processor3")).setPreferredLocation(new Point(516, 192));
        ((ViewableComponent)withName("transd")).setPreferredLocation(new Point(769, 203));
        ((ViewableComponent)withName("processor4")).setPreferredLocation(new Point(506, 265));
        ((ViewableComponent)withName("processor1")).setPreferredLocation(new Point(518, 22));
        ((ViewableComponent)withName("processor2")).setPreferredLocation(new Point(474, 93));
        ((ViewableComponent)withName("genr")).setPreferredLocation(new Point(50, 50));
    }
}
