package Lab4_HW;
import java.awt.*;
import simView.*;

public class gprocQt extends ViewableDigraph
{

	public gprocQt()
	{
		super("gprocQt");
    	
		ViewableAtomic g = new genr("g", 30);			//g보다 p가 커야 일이 쌓
		ViewableAtomic p = new procQ("p", 60);
		ViewableAtomic t = new transd("t", 5000);
    	
		add(g);
		add(p);
		add(t);
  
		addCoupling(g, "out", p, "in");
		addCoupling(g, "out", t, "ariv");
		
		addCoupling(p, "out", t, "solved");
     
		addCoupling(t, "out", g, "in");
	}

    
    /**
     * Automatically generated by the SimView program.
     * Do not edit this manually, as such changes will get overwritten.
     */
    public void layoutForSimView()
    {
        preferredSize = new Dimension(988, 646);
        ((ViewableComponent)withName("t")).setPreferredLocation(new Point(639, 117));
        ((ViewableComponent)withName("p")).setPreferredLocation(new Point(465, 476));
        ((ViewableComponent)withName("g")).setPreferredLocation(new Point(59, 148));
    }
}
