package Lab5_HW;
import java.awt.*;
import simView.*;

public class efQproc extends ViewableDigraph {

	
	public efQproc()
	{
		super("efQproc");
		
		
		//atiomic 모델 선언 여기서는 프로세스 하나 밖에 없음 
		ViewableAtomic Qproc = new procQ("Qproc",20);  //processing_time = 20
		
		//다이그래프 선언 , int_arr_time = 15, observation time = 500
		ViewableDigraph ef = new ef("ef",15,500);	//ef.java 에서 숫자를 변경해도 efp 가 더 상위개념이라 영향 없음. 
		
		//simulation view 에서 나오게 하기 , add() 는 atomic, digraph에 모두 적용되므로 용법 같음. 
	    add(Qproc);
	    add(ef); 
		
		//ef의 out과 Qproc의 in 연결 
	    addCoupling(ef,"out",Qproc, "in");
	    
	    //Qproc의 out과 ef 의 in 연결 
	    addCoupling(Qproc,"out",ef, "in");

		
	}
	
    /**
     * Automatically generated by the SimView program.
     * Do not edit this manually, as such changes will get overwritten.
     */
    public void layoutForSimView()
    {
        preferredSize = new Dimension(980, 644);
        ((ViewableComponent)withName("ef")).setPreferredLocation(new Point(105, 55));
        ((ViewableComponent)withName("Qproc")).setPreferredLocation(new Point(593, 353));
    }
    
}



