package Lab2;
import java.awt.*;
import simView.*;

public class gproc extends ViewableDigraph
{

	public gproc()
	{
		super("gproc");
    	
		
		//proc.java에서 20으로 초기화해줬지만 run 하면 10마다 반복됨. 이유? -> 자바는 Hierarchy 해서 상위(아래코드)레벨에서 언급한 것을 우선 받아들임.
		ViewableAtomic g = new genr("g", 30);	//devs java simulation viewer 에서 보이는 네모 박스의 존재함에 대한 것.
		ViewableAtomic p = new proc("p", 40);
		
		
		
		add(g);	//g박스가 보이도록 해주는 것. 위에서 선언을 해도 아래서 add 해주지 않으면 안 보일 것이다. 
		add(p);
		
  
		addCoupling(g, "out", p, "in");
		addCoupling(p, "out", g, "in");
	}

    
    /**
     * Automatically generated by the SimView program.
     * Do not edit this manually, as such changes will get overwritten.
     */
    public void layoutForSimView()
    {
        preferredSize = new Dimension(988, 646);
        ((ViewableComponent)withName("p")).setPreferredLocation(new Point(295, 168));
        ((ViewableComponent)withName("g")).setPreferredLocation(new Point(50, 50));
    }
}
